name: Check & fix styling

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "**.php"
      - "composer.lock"
      - ".github/workflows/lint.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**.php"
      - "composer.lock"
      - ".github/workflows/lint.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-lint:
    name: Check & fix styling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-php

      - uses: ./.github/actions/setup-composer

      - uses: ./.github/actions/validate-composer

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.6
        with:
          preset: psr12
          testMode: true
          useComposer: true
